# Task
task: example_3
instruction: "Stack all cubes on top of each other."
objects: 
  - "cubeA"
  - "cubeB"
  - "cubeC"
  - "table"
predicates:
  - "On(cubeA, table)"
  - "On(cubeB, table)"
  - "On(cubeC, table)"

# Behaviors
goals: [["Stacked(cubeB, cubeA)", "Stacked(cubeC, cubeB)"]]
plans: [["Pick(cubeB, table)", "Place(cubeB, cubeA)", "Pick(cubeC, table)", "Place(cubeC, cubeB)"]]
hypotheses: Null
geometric: Null

# OpenAI
role: system
name: Null
name_query: example_user
name_response: example_assistant
