prompt: BehaviorPromptManager
prompt_kwargs:
   # Task prompt
   task_prompt:
      # Task
      task: stack_task
      instruction: "Stack all cubes on top of each other"
      objects: 
         - "cubeA"
         - "cubeB"
         - "cubeC"
         - "table"
      predicates: 
         - "On(cubeA, table)"
         - "On(cubeB, table)"
         - "On(cubeC, table)"

      # Behaviors
      goals: Null
      plans: Null
      hypotheses: Null
      geometric: Null

      # OpenAI
      role: user
      name: Null
      name_query: Null
      name_response: Null
      
   # System prompts (relative to robosuite/planning directory)
   system_prompts:
      - configs/prompts/system/goal_prediction_v1.yaml
      - configs/prompts/system/task_planning_goal_condition_v1.yaml

   # Example prompts (relative to robosuite/planning directory)
   example_prompts:
      - configs/prompts/examples/example_1.yaml
      - configs/prompts/examples/example_2.yaml
      - configs/prompts/examples/example_3.yaml

   # Event prompts
   event_prompts: Null
